services:
  # Servicio de la API
  api:
    # Construye la imagen usando el Dockerfile del directorio actual
    build:
      context: .
      dockerfile: Dockerfile
    
    # Nombre del contenedor
    container_name: devops-api
    
    # Mapeo de puertos: HOST:CONTAINER
    ports:
      - "3000:3000"
    
    # Variables de entorno (opcional)
    environment:
      - NODE_ENV=production
      - PORT=3000
    
    # Reinicia automáticamente si el contenedor falla
    restart: unless-stopped
    
    # Healthcheck para verificar que la API está funcionando
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s